// <auto-generated />
using System;
using Infra.Repository.SqlServer.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infra.Repository.SqlServer.Core.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.BC.Domain.Entities.CatalogoEntidade", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<bool>("Ativo");

                    b.Property<bool>("Commited");

                    b.Property<DateTime>("Inicio");

                    b.Property<DateTime?>("InsertedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("InsertedAt");

                    b.Property<string>("InsertedUser")
                        .HasColumnName("CreatedUser")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<Guid?>("InsertedUserId")
                        .HasColumnName("CreatedUserId");

                    b.Property<string>("IntegrationCode")
                        .HasColumnType("varchar(120)")
                        .HasMaxLength(120);

                    b.Property<string>("NomeCatalogo");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnName("RemovedAt");

                    b.Property<DateTime>("Termino");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnName("LastUpdatedAt");

                    b.Property<string>("UpdatedUser")
                        .HasColumnName("LastUpdatedUser")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnName("LastUpdatedUserId");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationCode");

                    b.ToTable("CatalogoEntidade");
                });

            modelBuilder.Entity("Core.BC.Domain.Entities.ListaPrecoEntidade", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<Guid?>("CatalogoEntidadeId");

                    b.Property<bool>("Commited");

                    b.Property<decimal>("DescontoPercentual");

                    b.Property<DateTime>("Inicio");

                    b.Property<DateTime?>("InsertedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("InsertedAt");

                    b.Property<string>("InsertedUser")
                        .HasColumnName("CreatedUser")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<Guid?>("InsertedUserId")
                        .HasColumnName("CreatedUserId");

                    b.Property<string>("IntegrationCode")
                        .HasColumnType("varchar(120)")
                        .HasMaxLength(120);

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnName("RemovedAt");

                    b.Property<DateTime>("Termino");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnName("LastUpdatedAt");

                    b.Property<string>("UpdatedUser")
                        .HasColumnName("LastUpdatedUser")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnName("LastUpdatedUserId");

                    b.HasKey("Id");

                    b.HasIndex("CatalogoEntidadeId");

                    b.HasIndex("IntegrationCode");

                    b.ToTable("ListaPrecoEntidade");
                });

            modelBuilder.Entity("Core.BC.Domain.Entities.ProdutoListaPrecoModel", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<bool>("Commited");

                    b.Property<DateTime?>("InsertedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("InsertedAt");

                    b.Property<string>("InsertedUser")
                        .HasColumnName("CreatedUser")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<Guid?>("InsertedUserId")
                        .HasColumnName("CreatedUserId");

                    b.Property<string>("IntegrationCode")
                        .HasColumnType("varchar(120)")
                        .HasMaxLength(120);

                    b.Property<Guid?>("ListaPrecoEntidadeId");

                    b.Property<Guid?>("ProdutoId");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnName("RemovedAt");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnName("LastUpdatedAt");

                    b.Property<string>("UpdatedUser")
                        .HasColumnName("LastUpdatedUser")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnName("LastUpdatedUserId");

                    b.Property<decimal>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationCode");

                    b.HasIndex("ListaPrecoEntidadeId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ProdutoListaPrecoModel");
                });

            modelBuilder.Entity("Core.BC.Domain.Entities.ProdutoModel", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<Guid?>("CatalogoEntidadeId");

                    b.Property<string>("CodigoDeBarras")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("CodigoLote")
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("Commited");

                    b.Property<DateTime>("DataValidade");

                    b.Property<DateTime?>("InsertedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("InsertedAt");

                    b.Property<string>("InsertedUser")
                        .HasColumnName("CreatedUser")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<Guid?>("InsertedUserId")
                        .HasColumnName("CreatedUserId");

                    b.Property<string>("IntegrationCode")
                        .HasColumnType("varchar(120)")
                        .HasMaxLength(120);

                    b.Property<string>("NomeProduto");

                    b.Property<string>("NumeroDeSerie");

                    b.Property<bool>("Perecivel");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnName("RemovedAt");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnName("LastUpdatedAt");

                    b.Property<string>("UpdatedUser")
                        .HasColumnName("LastUpdatedUser")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnName("LastUpdatedUserId");

                    b.HasKey("Id");

                    b.HasIndex("CatalogoEntidadeId");

                    b.HasIndex("IntegrationCode");

                    b.ToTable("ProdutoModel");
                });

            modelBuilder.Entity("Core.BC.Domain.Entities.ProdutoVariacoesEntidade", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<bool>("Commited");

                    b.Property<DateTime?>("InsertedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("InsertedAt");

                    b.Property<string>("InsertedUser")
                        .HasColumnName("CreatedUser")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<Guid?>("InsertedUserId")
                        .HasColumnName("CreatedUserId");

                    b.Property<string>("IntegrationCode")
                        .HasColumnType("varchar(120)")
                        .HasMaxLength(120);

                    b.Property<string>("Nome");

                    b.Property<Guid?>("ProdutoId");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnName("RemovedAt");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnName("LastUpdatedAt");

                    b.Property<string>("UpdatedUser")
                        .HasColumnName("LastUpdatedUser")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnName("LastUpdatedUserId");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationCode");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ProdutoVariacoesEntidade");
                });

            modelBuilder.Entity("Core.BC.Domain.Entities.ListaPrecoEntidade", b =>
                {
                    b.HasOne("Core.BC.Domain.Entities.CatalogoEntidade")
                        .WithMany("ListaPreco")
                        .HasForeignKey("CatalogoEntidadeId");
                });

            modelBuilder.Entity("Core.BC.Domain.Entities.ProdutoListaPrecoModel", b =>
                {
                    b.HasOne("Core.BC.Domain.Entities.ListaPrecoEntidade")
                        .WithMany("ProdutoValor")
                        .HasForeignKey("ListaPrecoEntidadeId");

                    b.HasOne("Core.BC.Domain.Entities.ProdutoModel", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId");
                });

            modelBuilder.Entity("Core.BC.Domain.Entities.ProdutoModel", b =>
                {
                    b.HasOne("Core.BC.Domain.Entities.CatalogoEntidade")
                        .WithMany("Produtos")
                        .HasForeignKey("CatalogoEntidadeId");
                });

            modelBuilder.Entity("Core.BC.Domain.Entities.ProdutoVariacoesEntidade", b =>
                {
                    b.HasOne("Core.BC.Domain.Entities.ProdutoModel", "Produto")
                        .WithMany("Variacoes")
                        .HasForeignKey("ProdutoId");
                });
#pragma warning restore 612, 618
        }
    }
}
